# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: Lab4  

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x' 

- script: dotnet restore ./MVC_Agile_Process.csproj
  displayName: 'Restore packages'

- script: dotnet build ./MVC_Agile_Process.csproj --configuration Release
  displayName: 'Build solution'

- script: dotnet test ./MVC_Agile_Process.csproj
  displayName: 'Run tests'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'drop'
    targetPath: '$(Build.ArtifactStagingDirectory)'

